In [1]:
# IMporting Dataset
import pandas as pd
dataset = pd.read_csv("50_Startups.csv")

In [2]:
# Exploring dataset 
dataset.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [3]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   R&D Spend        50 non-null     float64
 1   Administration   50 non-null     float64
 2   Marketing Spend  50 non-null     float64
 3   State            50 non-null     object 
 4   Profit           50 non-null     float64
dtypes: float64(4), object(1)
memory usage: 2.1+ KB


In [4]:
# To get all columns
dataset.columns

Index(['R&D Spend', 'Administration', 'Marketing Spend', 'State', 'Profit'], dtype='object')

In [5]:
# We have to preprocess this state feature
state=dataset["State"]

In [6]:
# Importing LabelEncoder to do LabelEncoding 
from sklearn.preprocessing import LabelEncoder

In [7]:
state_le = LabelEncoder()
state_le_final = state_le.fit_transform(state)

In [8]:
state_le_final

array([2, 0, 1, 2, 1, 2, 0, 1, 2, 0, 1, 0, 1, 0, 1, 2, 0, 2, 1, 2, 0, 2,
       1, 1, 2, 0, 1, 2, 1, 2, 1, 2, 0, 1, 0, 2, 1, 0, 2, 0, 0, 1, 0, 2,
       0, 2, 1, 0, 2, 0])

In [10]:
state_le_final = state_le_final.reshape(-1,1)

In [11]:
state_le_final.shape

(50, 1)

In [12]:
# Now we have to do One Hot Encodin create dummy variable
from sklearn.preprocessing import OneHotEncoder

In [13]:
state_ohe = OneHotEncoder()

In [14]:
# Fit and transform
state_ohe_final = state_ohe.fit_transform(state_le_final)

In [15]:
# More no of zero in matrix so it is called Sparese Matrix
state_ohe_final

<50x3 sparse matrix of type '<class 'numpy.float64'>'
	with 50 stored elements in Compressed Sparse Row format>

In [17]:
# To print the matrix i.e DUMMY VARIABLE
state_final = state_ohe_final.toarray()

In [18]:
state_final

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0

In [22]:
# Now, we have to remove dependencies among feature i.e come out of Dummy Variable Trap 
# So, we have to remove any one coloumn. 
state_final_trap = state_final[:,0:2]  # array[no. of rows : no of columns ]  we can apply slicing concept here. 

In [23]:
y = dataset["Profit"]

In [24]:
X = dataset[ ["R&D Spend", "Administration", "Marketing Spend"] ]

In [25]:
X

R&D Spend  Administration  Marketing Spend
0   165349.20       136897.80        471784.10
1   162597.70       151377.59        443898.53
2   153441.51       101145.55        407934.54
3   144372.41       118671.85        383199.62
4   142107.34        91391.77        366168.42
5   131876.90        99814.71        362861.36
6   134615.46       147198.87        127716.82
7   130298.13       145530.06        323876.68
8   120542.52       148718.95        311613.29
9   123334.88       108679.17        304981.62
10  101913.08       110594.11        229160.95
11  100671.96        91790.61        249744.55
12   93863.75       127320.38        249839.44
13   91992.39       135495.07        252664.93
14  119943.24       156547.42        256512.92
15  114523.61       122616.84        261776.23
16   78013.11       121597.55        264346.06
17   94657.16       145077.58        282574.31
18   91749.16       114175.79        294919.57
19   86419.70       153514.11             0.00
20   76253.86       113867.30        298664.47
21   78389.47       153773.43        299737.29
22   73994.56       122782.75        303319.26
23   67532.53       105751.03        304768.73
24   77044.01        99281.34        140574.81
25   64664.71       139553.16        137962.62
26   75328.87       144135.98        134050.07
27   72107.60       127864.55        353183.81
28   66051.52       182645.56        118148.20
29   65605.48       153032.06        107138.38
30   61994.48       115641.28         91131.24
31   61136.38       152701.92         88218.23
32   63408.86       129219.61         46085.25
33   55493.95       103057.49        214634.81
34   46426.07       157693.92        210797.67
35   46014.02        85047.44        205517.64
36   28663.76       127056.21        201126.82
37   44069.95        51283.14        197029.42
38   20229.59        65947.93        185265.10
39   38558.51        82982.09        174999.30
40   28754.33       118546.05        172795.67
41   27892.92        84710.77        164470.71
42   23640.93        96189.63        148001.11
43   15505.73       127382.30         35534.17
44   22177.74       154806.14         28334.72
45    1000.23       124153.04          1903.93
46    1315.46       115816.21        297114.46
47       0.00       135426.92             0.00
48     542.05        51743.15             0.00
49       0.00       116983.80         45173.06

In [27]:
# We need to add state also in the features. We want to append horizontally 
import numpy
X = numpy.hstack((X,state_final_trap))

In [37]:
# Training & Testing split 
from sklearn.model_selection import train_test_split
X_train, X_test, y_train,y_test = train_test_split(X,y,test_size=0.2)

In [38]:
# to check shape of training data
X_train.shape

(40, 5)

In [39]:
# Model 
from sklearn.linear_model import LinearRegression

In [40]:
model = LinearRegression()

In [41]:
model.fit(X_train,y_train)

LinearRegression()

In [42]:
# Weight of each feature
# Now looking at this weight we can find max weight is of R&D Spend i.e around 8. 
#So, if increase 1unit on R&D it increase profit by 8 times.
model.coef_

array([ 7.94581814e-01, -6.09096879e-02,  2.85617357e-02,  1.25873892e+02,
        2.52027089e+02])

In [43]:
# Lets check prediction and find accuracy 

prediction = model.predict(X_test)

In [44]:
prediction

array([ 98469.57170298, 113586.94347084, 110445.52696216,  91521.54895812,
       187051.11807907,  91916.83486095,  59846.59048233, 135309.20684226,
       116580.47624743,  51548.96192436])